import type { Metadata } from 'next';
import { Cuprum } from 'next/font/google';
import './globals.css';

const inter = Cuprum({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${inter.className}  h-screen flex items-center justify-center bg-[url('/background.jpg')] bg-cover bg-center`}
			>
				<section className='max-w-screen-lg w-full mx-auto px-4'>{children}</section>
			</body>
		</html>
	);
}
